### ISSUE TITLE
Feature request: bash runtime

### ISSUE THREAD

**Issue by pjz** [runtools/run#2]
I like the idea of machine readable interoperability, but for legacy reasons I think there should be a bash runtime so that, for instance, a 'bzip' resource could be created to wrap the bzip command line.  If you feel like a challenge, try building a 'javac' or 'gcc' resource.

**Comment by mvila** [comment]
I totally agree with you, we need a `"shell/bash"` resource. 👍

**Comment by RobertFischer** [comment]
@mvila -- I was literally just coming to say this. I'm happy to implement it, if you can give me a starter for where to dig in.

**Comment by mvila** [comment]
OK after a good night's sleep, I come back here and wonder what exactly you guys want. 😄 

By "runtime", what do you mean?

It can be a simple **"resource"** (possibly named `"shell/bash"`) allowing to execute Bash commands.

For example, a resource wrapping `gzip` might look like this:

```js
{
  "compress": {
    "@type": "method",
    "@input": {
      "source": {
        "@type": "string",
        "@position": 0
      },
      "destination": {
        "@type": "string",
        "@position": 1
      }
    },
    "@run": "(@import shell/bash) run 'gzip -c ${source} > ${destination}'"
  },
  "uncompress": {
    // ...
  }
}
```

Or, it can be a **"resource runtime"** allowing to implement resource methods in Bash.

For example:

```js
{
  "@runtime": "bash",
  "@implementation": "./main.sh",
  "compress": {
    "@type": "method",
    "@input": {
      "source": {
        "@type": "string",
        "@position": 0
      },
      "destination": {
        "@type": "string",
        "@position": 1
      }
    }
  },
  "uncompress": {
    // ...
  }
}
```

Then, the implementation would be a bash script:

```bash
#!/bin/bash

compress ()
{
  gzip -c $1 > $2
}

uncompress ()
{
  # ...
}
```

The first possibility (a simple `"shell/bash"` resource) is super easy to implement.

The second possibility (a runtime for resources implemented in Bash) is a lot more complicated, and I am not sure that Bash can handle the whole resource specs.

**Comment by RobertFischer** [comment]
Oh, I'm sorry, I didn't quite understand the distinction.

I was thinking `resource runtime`, but a vanilla `resource` that allowed the execution of bash commands would be a good start. How about I create two issues, one for the `bash resource`, and another for a `bash resource runtime`, so we can keep those conversations distinct and separately track the orthogonal functionality?

I'd like to take a swing at the vanilla `resource`, if you don't mind. I'll name it `script/bash`, as per your recommendation.

**Comment by mvila** [comment]
If you are familiar with Node.js, you can create a resource to wrap Bash quite easily using something like `child_process.exec()`.

About creating two issues, I think it is a good idea, go on! 👍 

About the name of the `bash resource`, you cannot use the `script` (or `shell` as I thought at first) namespace directly, because it is reserved. So you should publish the resource with your personal namespace (e.g., `rfischer/bash`) at first. Then, I will check your resource, and if it looks fine, I will give you a `permissionToken` that will allow you to rename your resource to `script/bash` (or `shell/bash`?).

**Comment by mvila** [comment]
Since @RobertFischer forked this issue in #4 and #5, I am closing it.
