### ISSUE TITLE
Feature Request: Stack Resource and Haskell Runtime

### ISSUE THREAD

**Issue by RobertFischer** [runtools/run#3]
I do most of my development in Haskell, which is a nontrivial environment to manage. I'm excited about the possibility of using Run resources to manage them, since the dominant alternative (the Nix package manager) gives me a sad.

There are two pieces that I think we would need for this: first, a resource for supporting [stack](https://docs.haskellstack.org/en/stable/README/) builds; and second, a runtime resource that would execute a Haskell `*.hs` file (via `stack runghc`).

Two questions.

1) Are you interested in this?
2) Any tips on how to build this, what to name the resources, etc., etc.?

**Comment by mvila** [comment]
Thanks, @RobertFischer, it would be fantastic to build a Haskell runtime! 😄 But before going further, just to make sure we are on the same page, could you please have a look at [this comment](https://github.com/runtools/run/issues/2#issuecomment-373885923) and confirm what you actually want to build?

**Comment by RobertFischer** [comment]
Yeah, now that it's clearer to me, I am looking for three distinct things:

1. A `resource` that would wrap the configuration of [`cabal`](https://www.haskell.org/cabal/users-guide/developing-packages.html#package-descriptions) and [`stack`](https://docs.haskellstack.org/en/v1.0.4/yaml_configuration/#project-config) files, and possibly other common configuration options (eg: [`stylish-haskell`](https://github.com/jaspervdj/stylish-haskell/blob/master/README.markdown#configuration] and [`hlint`](https://github.com/ndmitchell/hlint#customizing-the-hints)). A lot of those have to be kept in sync in really obnoxious ways, and I'd like to have a single source of truth for configuration, and the relevant configuration files derived from there as needed.
1. A vanilla `resource` (or possibly a tight-knit family of resources?) that would allow the execution of `stack` commands. I'm envisioning a parent one that simply calls `stack` and feeds it various arguments, and then children of it for common stack commands (`build` for dev or prod, `test`, `watch`, `haddock`, `hoogle`, etc., etc.) so that you can be more declarative and clearer about what your options are.
1. A `resource runtime` that would allow for Haskell to be used as an implementation language for methods. This can be done through [`stack runghc`](https://haskell-lang.org/tutorial/stack-script), and is useful for leveraging my existing codebase for development tasks (eg: querying APIs with my client code to see how my client code understands the results).

So this should probably be three separate issues.

What do you think?

**Comment by mvila** [comment]
By "vanilla resource", what do you mean? If you mean a resource implemented in JS, I don't know if it is a good idea. I mean, don't you think it would make more sense to implement the resources managing Haskell tools using the Haskell language?

The problem is that right now, creating a resource runtime for Haskell is not an easy task, and maybe given the current state of the project it's not the right time:

* Resource's specs are not stable yet.
* The current implementation of Run is really rudimentary.
* Important parts like the interoperability between runtimes remain to be solved.

Of course, if you're not afraid to contribute to all this, then why not, we can work together. 😄

**Comment by RobertFischer** [comment]
By "vanilla resource", I mean a resource like the `script/bash` resource
discussed in the other thread - one that would let you execute a snippet of
Haskell code as an implementation for a method.

**Comment by RobertFischer** [comment]
And I am happy to work with you to push this project further: I think you
are onto something by abstracting and integrating the common parts of CLI
tooling.

**Comment by mvila** [comment]
Wow, I don't think you know what you're getting yourself into, but thank you so much. 😄 

So, if you want to embark on the adventure of creating a runtime, we have a lot to talk about. Would it be possible to arrange a call via Skype, Messenger, or something else? I think that at this stage of the project, it would be much more effective to talk directly. If you are okay with that, please contact me by [email](hi@mvila.me).

**Comment by RobertFischer** [comment]
Just reread this thread, and realized there was a slight miscommunication.

The "vanilla resource" was point 2 -- the `stack` commands. Those would build off of the resource coming out of issue #4. The runtime is #3.
