### ISSUE TITLE
Bash resource for method implementations

### ISSUE THREAD

**Issue by RobertFischer** [runtools/run#4]
This is fork 1 of 2 from #2. The goal is to provide a resource so that bash commands can be used to implement methods, such as this implementation for a `compress` method powered by `gzip`, implemented by calling out through the command line.

```json
{
  "compress": {
    "@type": "method",
    "@input": {
      "source": {
        "@type": "string",
        "@position": 0
      },
      "destination": {
        "@type": "string",
        "@position": 1
      }
    },
    "@run": "(@import shell/bash) run 'gzip -c ${source} > ${destination}'"
  },
  "uncompress": {
  }
}
```

Plan of attack is that I will create a resource named `robertfischer/bash` for @mvila to be review, and we will move that into `script/bash` once it looks good.

**Comment by RobertFischer** [comment]
@mvila  -- Do you have a good template resource for me to look into? I'm trying to figure out how to get some footing into the codebase.

**Comment by mvila** [comment]
Maybe the best would be to have a look at [`tool/console`](https://github.com/resdir/resdir/tree/master/resources/tool/console), it is extremely simple.

A few tips:
* `tool/console` imports [`1place/js-resource`](https://github.com/resdir/resdir/blob/master/resources/1place/js-resource) but you don't have to do the same. Have a look at the resource definition; it just adds a transpiler to make my life easier. I recommend you create your own starting point resources. It's not well established yet, but I think a good resource should have as little opinion as possible in the first place. For example, [`js/resource`](https://github.com/resdir/resdir/blob/master/resources/js/resource) includes `js/npm-dependencies` but not `js/transpiler`. Then, it is up to the user to add their opinions by extending the basic resources and publish these custom resources in their personal space.
* Once you have edited `src/index.js`, you can transpile it to `dist` by invoking `run @build`.
* To test your resource while you are building it, you can do something like `run \(@import .\) yourMethod someParams`. Or, you can create an [example resource](https://github.com/resdir/resdir/tree/master/resources/tool/console/example).
* You can go further by implementing automated tests. It's still very experimental and undocumented, but if you are curious, you can look how I test [`resdir/resource`](https://github.com/resdir/resdir/tree/master/resources/resdir/resource).
* In the `compress` example above, in `"(@import shell/bash) run 'gzip -c ${source} > ${destination}'"` I have used some variables (e.g., `${source}`) to pass the parameters, but this feature is actually not yet implemented. 😈 

Good luck! 😄
