### ISSUE TITLE
Bash Runtime Resource

### ISSUE THREAD

**Issue by RobertFischer** [runtools/run#5]
This is fork 2 of 2 from #2.

Quoting @mvila. The goal is to create...

> a "resource runtime" allowing to implement resource methods in Bash.
>
> For example:

```json
{
  "@runtime": "bash",
  "@implementation": "./main.sh",
  "compress": {
    "@type": "method",
    "@input": {
      "source": {
        "@type": "string",
        "@position": 0
      },
      "destination": {
        "@type": "string",
        "@position": 1
      }
    }
  },
  "uncompress": {
  }
}
```

> Then, the implementation would be a bash script:
>
```bash
#!/bin/bash

compress ()
{
  gzip -c $1 > $2
}

uncompress ()
{
  # ...
}
```
> A runtime for resources implemented in Bash is complicated,
> and I am not sure that Bash can handle the whole resource specs.

**Comment by mvila** [comment]
Thanks, @RobertFischer! Just one small detail, it might be clearer to remove the last two paragraphs. 😄

**Comment by RobertFischer** [comment]
I adjusted it to a paraphrase. :)
